export enum CivilStatusEnum {
	CIVIL_STATUS_WIDOWED =  'CIVIL_STATUS_WIDOWED',
	CIVIL_STATUS_SINGLE = 'CIVIL_STATUS_SINGLE',
	CIVIL_STATUS_MARRIED = 'CIVIL_STATUS_MARRIED',
	CIVIL_STATUS_DIVORCED = 'CIVIL_STATUS_DIVORCED'
}